
package serviceImpl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Wed May 12 21:25:33 WAT 2021
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "GenerateQuoteResponse", namespace = "http://serviceImpl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenerateQuoteResponse", namespace = "http://serviceImpl/")

public class GenerateQuoteResponse {

    @XmlElement(name = "return")
    private model.Quote _return;

    public model.Quote getReturn() {
        return this._return;
    }

    public void setReturn(model.Quote new_return)  {
        this._return = new_return;
    }

}

