
package serviceImpl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Fri May 14 00:55:38 WAT 2021
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "GetClientResponse", namespace = "http://serviceImpl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetClientResponse", namespace = "http://serviceImpl/")

public class GetClientResponse {

    @XmlElement(name = "return")
    private model.ReponseModelContryCode _return;

    public model.ReponseModelContryCode getReturn() {
        return this._return;
    }

    public void setReturn(model.ReponseModelContryCode new_return)  {
        this._return = new_return;
    }

}

