
package serviceImpl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Thu May 13 11:52:40 WAT 2021
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "GetFinalQuoteResponse", namespace = "http://serviceImpl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetFinalQuoteResponse", namespace = "http://serviceImpl/")

public class GetFinalQuoteResponse {

    @XmlElement(name = "return")
    private model.ResponseModel _return;

    public model.ResponseModel getReturn() {
        return this._return;
    }

    public void setReturn(model.ResponseModel new_return)  {
        this._return = new_return;
    }

}

